### ISSUE TITLE
Transmitter occasionally stops working when player is in other dimensions (possible bug)

### ISSUE THREAD

**Issue by farnoods** [starforcraft/Creative-Wireless-Transmitter#1]
Using the latest (1.02 version) of the mod on Minecraft 1.16.5 in All The Mods 6 (v1.5.3b) and the transmitter sometimes stops working while I'm in other dimensions (especially the Other dimension), I have a chunk loader at my base which is making sure the transmitter is always chunk loaded but this still happens. When I teleport back to my base to see what's up, I see that the transmitter is not lit up and I need to right click it once to light it back up. It's also getting ample power. Power's not an issue.

**Comment by starforcraft** [comment]
Hmm... okay thx for the report I will look into that :)

**Comment by farnoods** [comment]
Yeah. In order to recreate the bug, you'll need to spend some time in that dimension. When you first teleport to the dimension, everything will work fine, but after a while of flying and exploring that dimension, when you try to open the wireless grid, you'll get the 'failed to find a wireless transmitter in rage' error.

**Comment by starforcraft** [comment]
Hmm.. weird.. I also play ATM 6 sky and after like 30min in the Other everything works still fine (you dont need to use a Chunk Loader)

**Comment by farnoods** [comment]
That's weird. Here, I recorded a short demonstration video. It only took 7 minutes for mine to stop working. Here's the link to the video: https://youtu.be/qEx85Eav7uk

**Comment by starforcraft** [comment]
Wait.. did you claim your Chunks? It doesnt seem like it. In my World I have Claimed and Force loaded it

**Comment by starforcraft** [comment]
And can you maybe post the latest.log? on https://pastebin.com/ or other sites? So I can maybe find the error

**Comment by farnoods** [comment]
No I have claimed the chunks. I'm using JourneyMap for my mini map instead of the one you get from FTB Chunks, that's why you can't see it in the video, but my entire base is chunk claimed. Sure, I will send you the log when I get home. You want the server log, not the client log, correct?

**Comment by starforcraft** [comment]
yeah
