### ISSUE TITLE
Create Transmitter only works when vertical

### ISSUE THREAD

**Issue by DevPGSV** [starforcraft/Creative-Wireless-Transmitter#3]
When the Creative Wireless Transmitter is placed vertically on top of a Refined Storage block, it lights up and works correctly.
However, when it is placed on the side of a block and the orientation is horizontal, it doesn't light up, and it doesn't work.

**Comment by starforcraft** [comment]
![2022-03-18_18 02 51](https://user-images.githubusercontent.com/60074805/159049245-5030720a-d2f8-4f4a-82e8-c6e81af2df2d.png)

**Comment by starforcraft** [comment]
Doesn't seem like a bug to me lol
