### ISSUE TITLE
[BUG] [1.18.2] Advancement for transmitting wireless network signal between dimensions is bugged

### ISSUE THREAD

**Issue by Kanzaji** [starforcraft/Creative-Wireless-Transmitter#4]
Achievement "Why are you cheating bro?" is randomly being granted, when player joins the world, or does something random, like breaking a palm block.
*Relayed from Enigmatica 8: [#Enigmatica8/324](https://github.com/EnigmaticaModpacks/Enigmatica8/issues/324)

PS: Sorry, I missclicked enter after I wrote anything 😅

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter/files/4100669
